# Staging
apiVersion: v1
kind: ConfigMap
metadata:
  name: mini-eshop-config
  namespace: staging
data:
  NODE_ENV: staging
  DB_HOST: postgres-svc
  DB_PORT: "5432"
  DB_NAME: eshop_staging
---
# Production
apiVersion: v1
kind: ConfigMap
metadata:
  name: mini-eshop-config
  namespace: production
data:
  NODE_ENV: production
  DB_HOST: postgres-svc
  DB_PORT: "5432"
  DB_NAME: eshop_production
